"""create notion_credentials

Revision ID: 61976fb3be89
Revises: 
Create Date: 2026-02-27 16:40:44.248635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61976fb3be89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_name', sa.String(length=255), nullable=True),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notion_credentials_id'), 'notion_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_notion_credentials_user_id'), 'notion_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notion_credentials_user_id'), table_name='notion_credentials')
    op.drop_index(op.f('ix_notion_credentials_id'), table_name='notion_credentials')
    op.drop_table('notion_credentials')
    # ### end Alembic commands ###
