"""add notion database id

Revision ID: a86c56e33015
Revises: 61976fb3be89
Create Date: 2026-02-27 17:31:35.692134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86c56e33015'
down_revision: Union[str, Sequence[str], None] = '61976fb3be89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notion_credentials', sa.Column('database_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_notion_credentials_database_id'), 'notion_credentials', ['database_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notion_credentials_database_id'), table_name='notion_credentials')
    op.drop_column('notion_credentials', 'database_id')
    # ### end Alembic commands ###
